imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    token_api_clash: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImEwOGIwY2QyLTNkN2MtNDQ2Yy1hNDZhLTUzNGU1NGU1M2IxYSIsImlhdCI6MTQ4MzYzODI4NSwic3ViIjoiZGV2ZWxvcGVyLzRlZTViYzAwLTU4M2ItMDM5NS0yZTA1LTQwYzYwYjgxOWJmOSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjIxNy43MC4xODAuMjI2IiwiODkuMy4yMzguMTEiLCIxODUuNzQuNDIuODIiLCI4Mi42Ni4xMTIuMzgiXSwidHlwZSI6ImNsaWVudCJ9XX0.O6bmyP3FoC5z5nYWjTniqfroQe4QyqWDiOTfOKGEgICXgf-HdzXrYyZrJ4nSpQcgdGrsb34ab4oQ5tAN52JqXg

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - "BzhCoreBundle::bootstrap_4_horizontal_layout.html.twig"
    globals:
        webmaster: Gus
        version: 0.0.1

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Stof\DoctrineExtensionsBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true
            tree: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        jsqueeze:   ~
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'

ivory_ck_editor:
    configs:
        my_config:
            toolbar: [ ["Bold", "Italic", "Underline", "Strike", "-", "RemoveFormat"], ["Styles"],["Format"],["Font"],["FontSize"],["TextColor","BGColor"], "/", ["NumberedList", "BulletedList", "-", "Outdent", "Indent" , "-", "Blockquote", "CreateDiv", "-", "JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock"], ["Link","Unlink","Anchor"], ["Image","Table","HorizontalRule","SpecialChar","Smiley"] ]
        full:
             toolbar: full
# "/" => new line
# "-" => séparation
