fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

bzh_war:
    resource: "@BzhWarBundle/Resources/config/routing.yml"
    prefix:   /war

core:
    resource: "@BzhCoreBundle/Resources/config/routing.yml"
    prefix:   /