home:
    path:     /
    defaults: { _controller: BzhCoreBundle:Core:index }

clan:
    path:     /{slug}
    defaults: { _controller: BzhCoreBundle:Core:clan }
    
clan_players:
    path:     /{slug}/members
    defaults: { _controller: BzhCoreBundle:Core:members }
    
clan_warlog:
    path:     /{slug}/warlog
    defaults: { _controller: BzhCoreBundle:Core:warlog }
    
    