home:
    path:     /
    defaults: { _controller: BzhCoreBundle:Core:index }
    
map:
    path:     /map
    defaults: { _controller: BzhCoreBundle:Core:map }

matchmaking:
    path:     /matchmaking
    defaults: { _controller: BzhCoreBundle:Core:matchmaking }    
    
clan:
    path:     /{slug}
    defaults: { _controller: BzhCoreBundle:Core:clan }
    
clan_members:
    path:     /{slug}/members
    defaults: { _controller: BzhCoreBundle:Core:members }

clan_members_update:
    path:     /{slug}/members/update
    defaults: { _controller: BzhCoreBundle:Core:membersUpdate }
    
clan_warlog:
    path:     /{slug}/warlog
    defaults: { _controller: BzhCoreBundle:Core:warlog }
    
clan_stats:
    path:     /{slug}/stats
    defaults: { _controller: BzhCoreBundle:Core:stats }
    
clan_rules:
    path:     /{slug}/regles
    defaults: { _controller: BzhCoreBundle:Core:rules }