home:
    path:     /
    defaults: { _controller: BzhCoreBundle:Core:index }

core_clan:
    path:     /clan/{slug}
    defaults: { _controller: BzhCoreBundle:Core:clan }
    
players:
    path:     /clan/{slug}/members
    defaults: { _controller: BzhCoreBundle:Core:members }