war_new:
    path:     /new
    defaults: { _controller: BzhWarBundle:War:new }

war_code:
    path:     /{code}
    defaults: { _controller: BzhWarBundle:War:code }
    
war_edit:
    path:     /{code}/edit
    defaults: { _controller: BzhWarBundle:War:edit }

war_delete:
    path:     /{code}/delete
    defaults: { _controller: BzhWarBundle:War:delete }
    
war_clan_description:
    path:     /{code}/clan-description
    defaults: { _controller: BzhWarBundle:War:clanDescription }
    
war_target_comment:
    path:     /target-comment/{id}
    defaults: { _controller: BzhWarBundle:War:targetComment }
    options:
        expose: true
        
war_target_hdv:
    path:     /{code}/target-hdv/{id}
    defaults: { _controller: BzhWarBundle:War:targetHdv }
    options:
        expose: true
        
war_target_attack:
    path:     /{code}/target-attack/{id}
    defaults: { _controller: BzhWarBundle:War:targetAttack }
    options:
        expose: true

war_delete_attack:
    path:     /{code}/delete-attack/{id}
    defaults: { _controller: BzhWarBundle:War:deleteAttack }
    options:
        expose: true
        
war_edit_attack:
    path:     /{code}/edit-attack/{id}
    defaults: { _controller: BzhWarBundle:War:editAttack }
    options:
        expose: true

war_result_attack:
    path:     /{code}/result-attack/{id}
    defaults: { _controller: BzhWarBundle:War:resultAttack }
    options:
        expose: true