services:
    
    war.code.new:
        class: Bzh\WarBundle\Services\CreateWarCode
        arguments: [4]
        
    war.targets.create:
        class: Bzh\WarBundle\Services\CreateTargets
        arguments: [ "@doctrine.orm.entity_manager" ]
        
    war.dates.calc:
        class: Bzh\WarBundle\Services\CalcDateTime
    
    war.dates.twig.extension:
        class: Bzh\WarBundle\Twig\CalcDateTimeExtension
        arguments:
            - "@war.dates.calc"
        tags:
            -  { name: twig.extension }
