<?php

namespace Bzh\CoreBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Change le champ OLD pour tous les PLAYER d'un CLAN
     * @param \Bzh\CoreBundle\Entity\Clan $clan
     * @param type $value
     * @return type
     */
    public function setOldAllPlayers(\Bzh\CoreBundle\Entity\Clan $clan, $value) {
        return $this->createQueryBuilder('u')
            ->update()
            ->where('u.clan = :clan')
                ->setParameter(":clan", $clan)
            ->set('u.old', ':old')
                ->setParameter(":old", $value)
            ->getQuery()->getSingleScalarResult();
    }
    
    public function getPlayers(\Bzh\CoreBundle\Entity\Clan $clan, $value) {
        return 
            $this->findBy(array(
                'clan' => $clan,
                'old' => $value
            ), array(
                'trophies' => 'desc',
                'bestTrophies' => 'desc',
                'name' => 'asc'
            ));
    }
}
